/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package runsql_anony;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author hv655
 */
public class qryLightAbout extends javax.swing.JPanel {

    /**
     * Creates new form qryLightAbout
     */
    public qryLightAbout() {
        initComponents();
        ImageIcon icon =new ImageIcon(getClass().getResource("/runsql_anony/db1-icon.png"));
           Image img=icon.getImage();
           Image newimg = img.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
           icon = new ImageIcon(newimg);
           lblIcon.setIcon(icon);
           vLicenseText.setCaretPosition(1);
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vLicenseText = new javax.swing.JTextArea();
        ldesc = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblIcon.setText(" ");
        add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 41, 39, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Query Light");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Version : 1.0.0");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 137, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Developed By : Milind Brahme");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, 198, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Email : milind.brahme@gmail.com");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 198, -1));

        jLabel5.setText("GNU GENERAL PUBLIC LICENSE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 209, -1));

        vLicenseText.setEditable(false);
        vLicenseText.setColumns(20);
        vLicenseText.setRows(5);
        vLicenseText.setText("Query Light - Oracle Lightweight Client and Editor\nCopyright (C) 2015  Milind M. Brahme\n\nThis program is free software; you can redistribute it and/or\nmodify it under the terms of the GNU General Public License\nas published by the Free Software Foundation; either version 2\nof the License, or (at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program; if not, write to the Free Software\nFoundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.");
        vLicenseText.setOpaque(false);
        jScrollPane1.setViewportView(vLicenseText);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 535, 111));

        ldesc.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ldesc.setText("Oracle Lightweight Client and Editor.");
        add(ldesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 262, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel ldesc;
    private javax.swing.JTextArea vLicenseText;
    // End of variables declaration//GEN-END:variables
}
